Models/ErrorViewModel.cs
namespace Online_Job_Portal.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Job.cs
namespace Online_Job_Portal.Models
{
    public class Job
    {
        public int JobId { get; set; }
        public string JobName { get; set; }
        public string JobDescription { get; set; }

        public double JobSalary { get; set; }
        public int CompanyId { get; set; }
        public string CompanyName { get; set;}
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Online_Job_Portal.Models;
using System.Diagnostics;

namespace Online_Job_Portal.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/JobController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.Identity.Client;
using Online_Job_Portal.Models;

namespace Online_Job_Portal.Controllers
{
    public class JobController : Controller
    {
        //private  List<Job> JobList = new List<Job>();
        private IConfiguration Configuration;
        public JobController(IConfiguration configuration)
        {
            Configuration = configuration;
        }
        public IActionResult AddJobs()
        {
            string Message = " ";
            bool Error = false;
            if (Request.Method == "POST")
            {
                Job job = new Job();
                job.JobName = Request.Form["JobName"];
                job.JobDescription = Request.Form["JobDescription"];
                job.JobSalary = Convert.ToDouble(Request.Form["JobSalary"]);
                job.CompanyId = Convert.ToInt32(Request.Form["CompanyId"]);
                try
                {
                    using (SqlConnection sqlConnection = new SqlConnection(Configuration.GetConnectionString("Online_Job_Portal")))
                    {
                        sqlConnection.Open();
                        using (SqlCommand cmd = sqlConnection.CreateCommand())
                        {
                            Console.WriteLine(job.JobDescription);
                            cmd.CommandText = $"INSERT INTO JOBS VALUES('{job.JobName}','{job.JobDescription}',{job.JobSalary},{job.CompanyId})";
                            cmd.ExecuteNonQuery();
                            Message = "Added Successfully";
                        }
                    }
                }
                catch (SqlException ex)
                {
                    Message="Error with SQL SERVER";
                    Console.WriteLine(ex.Message);
                    Error = true;
                }
                catch (Exception ex)
                {
                    Message = "Error While Adding Job";
                    Console.WriteLine(ex.Message);
                    Error = true;
                }
            
            }
            ViewData["Message"]=Message;
            ViewData["Error"]=Error;


            return View();
        }

        private List<Job> getJobs() {
           
            List<Job> JobsList = new List<Job>();
            try
            {
                using (SqlConnection sqlConnection = new SqlConnection(Configuration.GetConnectionString("Online_Job_Portal")))
                {
                    sqlConnection.Open();
                    using (SqlCommand cmd = sqlConnection.CreateCommand())
                    {
                        cmd.CommandText = "SELECT * FROM JOBS INNER JOIN COMPANIES ON JOBS.COMPANY_ID=COMPANIES.COMPANY_ID";
                        SqlDataReader reader = cmd.ExecuteReader();
                        while (reader.Read())
                        {
                            Job job = new Job();
                            job.JobId = (int)reader["JOB_ID"];
                            job.JobName = (string)reader["JOB_NAME"];
                            job.JobDescription = (string)reader["JOB_DESCRIPTION"];
                            job.JobSalary = (double)reader["JOB_SALARY"];
                            job.CompanyName = (string)reader["COMPANY_NAME"];
                            JobsList.Add(job);
                        }
                    }
                }
            }
            catch (SqlException ex)
            {
                Console.WriteLine(ex.Message);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            return JobsList;
        } 
        public IActionResult DisplayJobs()
        {

            
            ViewBag.JobList = getJobs();
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Id = id;
            ViewBag.JobList = getJobs();
            return View();
        }


        public void updateJob(Job job)
        {
            using (SqlConnection sqlConnection = new SqlConnection(Configuration.GetConnectionString("Online_Job_Portal")))
            {

                using (SqlCommand cmd = sqlConnection.CreateCommand())
                {
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;
                    cmd.CommandText = "updateJob";

                    cmd.Parameters.AddWithValue("@JOB_ID", job.JobId);
                    cmd.Parameters.AddWithValue("@JOB_NAME", job.JobName);
                    cmd.Parameters.AddWithValue("@JOB_DESCRIPTION", job.JobDescription);
                    cmd.Parameters.AddWithValue("@JOB_SALARY", job.JobSalary);

                    // Not used in the procedure
                    cmd.Parameters.AddWithValue("@COMPANY_ID", job.CompanyId);

                    sqlConnection.Open();
                    cmd.ExecuteNonQuery();
                    sqlConnection.Close();

                }
            }
        }


        [HttpPost]
        public IActionResult Edit(int id, IFormCollection form)
        {
            try
            {

                Job job = new Job() {   JobId= Convert.ToInt32( form["jobId"]) ,JobDescription= form["jobDescription"], JobName= form["jobName"]   ,
                    
                    JobSalary = Convert.ToInt32(form["jobSalary"]),
                    CompanyId = Convert.ToInt32(form["companyId"])

                };
                updateJob(job);
                return RedirectToAction("DisplayJobs");
            }catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
                return View();
            }
        }


        private void deleteJob(int jobId)
        {

            using (SqlConnection sqlConnection = new SqlConnection(Configuration.GetConnectionString("Online_Job_Portal")))
            {
                
                using (SqlCommand cmd = sqlConnection.CreateCommand())
                {
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;
                    cmd.CommandText= "deleteJob";

                    cmd.Parameters.AddWithValue("@JOB_ID",jobId);

                    sqlConnection.Open();
                    cmd.ExecuteNonQuery();
                    sqlConnection.Close();

                }
            }

        }

        public IActionResult Delete(int id)
        {
            try
            {
                deleteJob(id);
                return RedirectToAction("DisplayJobs");
            }catch (Exception ex)
            {
                return View();
            }

        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Job/AddJobs.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form class="form-text" method="post">
    <div class="row mb-3">

        <div class="input-group-sm">
            <label class="col-form-label-sm">Job Name</label>
            <input type="text" name="JobName" placeholder="Enter Job Name" required /><br>
        </div>
    </div>
    <div class="row mb-3">

        <div class="input-group-sm">
            <label class="col-form-label-sm">Job Description</label><br>
            <textarea name="JobDescription" placeholder="Enter Job Description" required></textarea><br>
        </div>
    </div>
    <div class="row mb-3">

        <div class="input-group-sm">
            <label class="col-form-label-sm">Job Salary</label>
            <input type="number" step=any name ="JobSalary" placeholder="Enter Salary" required /><br>
        </div>
    </div>
    <div class="row mb-3">

        <div class="input-group-sm">
            <label class="col-form-label-sm">Company Id</label>
            <input type="number" name="CompanyId" placeholder="Enter Company Id" required /><br>
        </div>
    </div>
    @if (ViewData["Message"].ToString().Length > 1 && (ViewBag.Error))
    {
        <div class="error-dic">
            <div class="alert-warning" id="alert">
                <label style="color:red">@ViewData["Message"].ToString().</label>
                <button class="btn-close" data-dismiss="alert" onclick="document.getElementById('alert').remove()">Close</button>
            </div>
        </div>
    }

    else if (ViewData["Message"].ToString().Length > 1)
    {
        <div class="error-dic">
            <div class="alert-warning" id="alert">
                <label style="color:green">@ViewData["Message"].ToString()</label>
                <button class="btn-close" data-dismiss="alert" onclick="document.getElementById('alert').remove()">Close</button>
            
            </div>
        </div>
    }
    <div class="row mb-3">

        <div class="input-group-sm">
            <button class="btn-primary" type="submit">Submit</button>
        </div>
    </div>
</form>

Views/Job/DisplayJobs.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
}
<br>
<h1>Jobs List</h1>
<a href="/Job/AddJobs" class="btn btn-primary" role="button">Add Jobs</a>
<table class="table">
    <thead>
        <tr>
            <th>Job Id</th>
            <th>Job Name</th>
            <th>Job Description</th>
            <th>Salary(LPA)</th>
            <th>Company Name</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Job job in (List<Job>)ViewBag.JobList)
        {
            <tr>
                <td>@job.JobId</td>
                <td>@job.JobName</td>
                <td>@job.JobDescription</td>
                <td>@job.JobSalary</td>
                <td>@job.CompanyName</td>
                <td> <button class="btn btn-danger btn-sm"  onclick='myDelete("/Job/Delete/@job.JobId","@job.JobId")'>delete</button>  </td>
                <td> <a class="btn btn-primary btn-sm" role="button"  href="/Job/Edit/@job.JobId">Edit</a>  </td>
            </tr>
        }
    </tbody>

</table>

<script>
    function myDelete(link, id) {
        let text = "Are you sure you want to delete book " + id + " ?";
        let _link = link;
        if (confirm(text) == true) {

            window.open(link, '_self');
        }
    }
</script>

Views/Job/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
}
<br>
<h1>Jobs List</h1>
<a href="/Job/AddJobs" class="btn btn-primary" role="button">Add Jobs</a>
<table class="table">
    <thead>
        <tr>
            <th>Job Id</th>
            <th>Job Name</th>
            <th>Job Description</th>
            <th>Salary(LPA)</th>
            <th>Company Name</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Job job in (List<Job>)ViewBag.JobList)
        {
            <tr>
            @if( job.JobId == ViewBag.Id ){
                    <form method="post" action="/Job/Edit/@job.JobId">
                    <td>
                        <input type="number" value="@job.JobId" name="jobId" readonly />
                    </td>

                    <td>
                        <input type="text" value="@job.JobName" name="jobName" placeholder="job name"  />
                    </td>

                    <td>
                        <textarea type="text"  placeholder="job description" name="jobDescription">@job.JobDescription</textarea>
                    </td>

                    <td>
                        <input type="number" value="@job.JobSalary" placeholder="salary" name="jobSalary" step="any" />
                    </td>

                    <td>
                        <input type="text" value="@job.CompanyName" placeholder="Company name" name="jobCompany" readonly/>
                    </td>
                    <td> 
                        <button class="btn btn-primary btn-sm"  type="submit"  >Apply</button>  
                    </td>
                   </form>


            }
            else
            {
                
                    <td>@job.JobId</td>
                    <td>@job.JobName</td>
                    <td>@job.JobDescription</td>
                    <td>@job.JobSalary</td>
                    <td>@job.CompanyName</td>
                    <td> <button class="btn btn-sm btn-danger"  onclick='myDelete("/Job/Delete/@job.JobId","@job.JobId")'>delete</button>  </td>
                
            }
            </tr>
        }
    </tbody>

</table>

<script>
    function myDelete(link, id) {
        let text = "Are you sure you want to delete book " + id + " ?";
        let _link = link;
        if (confirm(text) == true) {

            window.open(link, '_self');
        }
    }
</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Online_Job_Portal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Online_Job_Portal.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Online Job Portal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Job" asp-action="DisplayJobs">Job</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Online_Job_Portal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>